name: Website Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install html-linter
          pip install cssutils
          npm install -g stylelint stylelint-config-standard stylelint-config-recommended
          npm install -g htmlhint

      - name: Lint CSS files
        id: csslint
        continue-on-error: true # Don't fail the workflow, but track result
        run: |
          echo "Running CSS linting..."
          # Create a minimal stylelint configuration
          cat > .stylelintrc.json << EOF
          {
            "extends": "stylelint-config-recommended",
            "rules": {
              "no-descending-specificity": null,
              "no-duplicate-selectors": null,
              "font-family-no-missing-generic-family-keyword": null,
              "property-no-vendor-prefix": null,
              "color-function-notation": null,
              "alpha-value-notation": null,
              "media-feature-range-notation": null,
              "selector-not-notation": null
            }
          }
          EOF

          npx stylelint "styles.css" || echo "CSS linting found issues"
          echo "CSS linting completed"

      - name: Lint HTML templates
        id: htmllint
        continue-on-error: true # Don't fail the workflow, but track result
        run: |
          echo "Running HTML linting..."

          # Create HTMLHint configuration to ignore certain rules
          cat > .htmlhintrc << EOF
          {
            "tagname-lowercase": true,
            "attr-lowercase": true,
            "attr-value-double-quotes": true,
            "attr-no-duplication": true,
            "tag-pair": true,
            "spec-char-escape": false,
            "id-unique": true,
            "src-not-empty": true,
            "title-require": true,
            "alt-require": true,
            "doctype-html5": true,
            "style-disabled": false,
            "space-tab-mixed-disabled": true,
            "attr-unsafe-chars": true
          }
          EOF

          htmlhint "templates/*.html" || echo "HTML linting found issues"
          echo "HTML linting completed"

      - name: Check if all quality checks passed
        id: check_results
        run: |
          if [[  "${{ steps.csslint.outcome }}" == "success" && "${{ steps.htmllint.outcome }}" == "success" ]]; then
            echo "All quality checks passed successfully!"
            echo "all_checks_passed=true" >> $GITHUB_OUTPUT
          else
            echo "Some quality checks failed. Check the logs for details."
            echo "all_checks_passed=false" >> $GITHUB_OUTPUT
            
            # Create summary of issues
            echo "### Quality Check Results" >> $GITHUB_STEP_SUMMARY
            echo "- Spellcheck: ${{ steps.spellcheck.outcome }}" >> $GITHUB_STEP_SUMMARY
            echo "- CSS Lint: ${{ steps.csslint.outcome }}" >> $GITHUB_STEP_SUMMARY
            echo "- HTML Lint: ${{ steps.htmllint.outcome }}" >> $GITHUB_STEP_SUMMARY
          fi

    outputs:
      all_checks_passed: ${{ steps.check_results.outputs.all_checks_passed }}

  # Trigger deployment workflow if on main branch and all checks pass
  trigger-deployment:
    needs: quality-checks
    if: github.ref == 'refs/heads/main' && needs.quality-checks.outputs.all_checks_passed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: auto-deploy
          client-payload: '{"auto_triggered": true}'
